# Generated by Django 4.0.3 on 2022-04-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='date',
        ),
        migrations.AlterField(
            model_name='library',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
